import {
  Bell,
  Camera,
  Clock,
  Building2,
  CreditCard,
  DollarSign,
  Edit,
  Eye,
  Check,
  CircleAlert,
  CircleHelp,
  FileText,
  Flame,
  Gift,
  Heart,
  Image,
  LayoutDashboard,
  KeyRound,
  LockKeyhole,
  Mail,
  MapPin,
  MousePointer2,
  Package,
  Search,
  Save,
  Send,
  Settings,
  ShoppingCart,
  Shield,
  Smartphone,
  Tag,
  Trash2,
  Ticket,
  Toolbox,
  User,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react"

const ICONS: Record<string, LucideIcon> = {
  alert: CircleAlert,
  bell: Bell,
  building: Building2,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  eye: Eye,
  check: Check,
  camera: Camera,
  clock: Clock,
  dashboard: LayoutDashboard,
  document: FileText,
  edit: Edit,
  flame: Flame,
  gift: Gift,
  heart: Heart,
  image: Image,
  location: MapPin,
  key: KeyRound,
  lock: LockKeyhole,
  mail: Mail,
  package: Package,
  mouse: MousePointer2,
  search: Search,
  save: Save,
  send: Send,
  settings: Settings,
  shoppingCart: ShoppingCart,
  shield: Shield,
  tag: Tag,
  ticket: Ticket,
  trash: Trash2,
  toolbox: Toolbox,
  user: User,
  users: Users,
  wallet: Wallet,
  smartphone: Smartphone,
  zap: Zap,
  help: CircleHelp,
}

interface AppIconProps {
  name: string
  className?: string
  size?: number
  strokeWidth?: number
}

export function AppIcon({ name, className, size, strokeWidth }: AppIconProps) {
  const Icon = ICONS[name] ?? CircleHelp
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />
}
